# Generated by Django 3.1.3 on 2021-01-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210102_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.myuser'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('T-shirts', 'T-shirts'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes')], default='', max_length=10),
        ),
    ]
