# Generated by Django 3.1.3 on 2021-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_myuser_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('W', 'Women'), ('M', 'Men'), ('K', 'Kid')], default='null', max_length=5),
        ),
    ]
