# Generated by Django 3.1.3 on 2021-01-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20210115_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('T-shirts', 'T-shirts'), ('Jackets', 'Jackets'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Tights', 'Tights'), ('Trousers', 'Trousers'), ('Joggers', 'Joggers'), ('Sneakers', 'Sneakers'), ('Pumps', 'Pumps'), ('Heels', 'Heels')], default='', max_length=10),
        ),
    ]
