# Generated by Django 3.1.3 on 2021-01-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20210117_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
